name: flutter_app
description: UniEventAI mobil uygulaması
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.1
  google_maps_flutter: ^2.5.0
  intl: ^0.20.2
  url_launcher: ^6.1.14
  shared_preferences: ^2.1.0
  image_picker: ^1.2.2
  google_nav_bar: ^5.0.7
  google_fonts: ^8.0.2
  line_icons: ^2.0.3
  flutter_card_swiper: ^7.2.0
  sensors_plus: ^7.0.0
  fl_chart: ^1.2.0
  qr_flutter: ^4.1.0
  screen_brightness: ^2.1.7
  flutter_secure_storage: ^10.0.0
  cached_network_image: ^3.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/map_style/dark_neon_style.json
  shaders:
    - assets/shaders/fluid_wave.frag

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
